### ISSUE TITLE
Release 1.7.1

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/billing-ill#109]
### Descriptive summary

Version: 1.7.1
Release Manager: @hweng  
Product Owner: @mcritchlow 
Operations: @jhriv 

Addresses Nokigiri security vulnerability via #108

**Comment by hweng** [comment]
@jhriv The new release has been merged into master branch. Could you please deploy it? Thanks

**Comment by jhriv** [comment]
Deployed to production
https://ucsdlibrary.slack.com/archives/G0N0H8LHF/p1491326922868502
