### ISSUE TITLE
Release 1.7.2

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/billing-ill#113]
ILL Billing Version: 1.7.2
Release Manager: @hweng 
Product Owner and Reviewers: @mcritchlow
Operations: @jhriv  

This is a dependency update release. But would be nice if someone could give it a once over. With Roger gone, who would do this, @hweng ?

**Comment by hweng** [comment]
@mcritchlow As Encinas, Isabel informed me that she is responsible for ILL Billing. I think she would be a good person to do it, right?

**Comment by mcritchlow** [comment]
@hweng - yes that would be great if she can. Just a basic review of the functionality. I'm sure everything is fine, a nice safety check if she's up for it.

**Comment by hweng** [comment]
@mcritchlow The release has been deployed to staging.  Would you ask Encinas, Isabel to review it on test environment?

**Comment by hweng** [comment]
@jhriv The latest updates has been merged into master branch. It is ready to deploy to production. Thank you!

**Comment by jhriv** [comment]
Deployed (2017-05-16 https://gist.github.com/7333ae0e3bfe23e5b493227fd56789e6)
