### ISSUE TITLE
Release 1.7.5

### ISSUE THREAD

**Issue by hweng** [ucsdlib/billing-ill#119]
### Descriptive summary

Version: 1.7.5
Release Manager: @hweng  
Product Owner: @mcritchlow 
Operations: @jhriv 

Fix log in issues via #118

**Comment by hweng** [comment]
@jhriv, This release includes a fix to the log in issue. The release is merged into master branch. Could you please deploy it to the production at your earliest convenience? The staff told me that they need to access to the ILL billing program now because they have a patron wanting to get a copy of their current invoice. Thanks!

**Comment by jhriv** [comment]
Deployed.

**Comment by hweng** [comment]
Thanks @jhriv
