### ISSUE TITLE
Release 1.7.6

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/billing-ill#124]
### Descriptive summary

Release Manager: @hweng
Product Owner: @mcritchlow
Operations: @jhriv

- https://github.com/ucsdlib/billing-ill/tree/release/1.76

**Comment by hweng** [comment]
The release 1.7.6 has been created and deployed to staging. 
@EncinasIsabel Could you please review and approve it? Thanks!

**Comment by EncinasIsabel** [comment]
The test worked fine, thank you Huawei!

**Comment by hweng** [comment]
@jhriv The release has been merged into master branch, and passed circleci test. It is ready to deploy to production. Thanks!
