### ISSUE TITLE
Release 1.77

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/billing-ill#127]
### Descriptive summary

Release Manager: @hweng
Product Owner: @EncinasIsabel 
Operations: @jhriv

### Features/Bug Fixes to verify:
- [ ] #125 (updated email template)

**Comment by hweng** [comment]
@EncinasIsabel, The release 1.77 has deployed which include the updates to https://github.com/ucsdlib/billing-ill/issues/125. Could you review and approve the build?Thanks!

**Comment by hweng** [comment]
@EncinasIsabel, The staging url is http://librarytest.ucsd.edu/billing-ill

**Comment by EncinasIsabel** [comment]
Thank you Huawei, the test message looks correct and ready to deploy.  Thank you!

**Comment by hweng** [comment]
Thanks @EncinasIsabel for reviewing.
@jhriv The release 1.77 has been merged into master branch. It is ready to deploy to production.

**Comment by mcritchlow** [comment]
@hweng @jhriv - did this go to production? Noticed the ticket is still open

**Comment by jhriv** [comment]
I think it went out on the 5th. Is there a way to verify the version number in the app?

**Comment by mcritchlow** [comment]
Merge commits aside, it looks like master has the latest commits from develop with the release number tagged here in the merge commit. So I suspect we're good, just wanted to verify with ya'll

**Comment by jhriv** [comment]
Deployed (2017-09-05)
