### ISSUE TITLE
New contact information for ILL Billing File

### ISSUE THREAD

**Issue by EncinasIsabel** [ucsdlib/billing-ill#131]
Hi Huawei,

Can you please replace my contact information on the automated email message that appears after Invoices or Recharges are processed through FTP to ACT?  The new contact information should be as follows:
NAME: Lilly S. Chodur
EMAIL: lchodur@ucsd.edu
PHONE: (858) 534-5902
MAIL CODE: 0175-A

Thank you!

Isabel

**Comment by hweng** [comment]
@EncinasIsabel Sure. I will update it and let you know when it is done.

**Comment by EncinasIsabel** [comment]
Thank you Huawei!
