### ISSUE TITLE
Correction to ILL invoice template text

### ISSUE THREAD

**Issue by EncinasIsabel** [ucsdlib/billing-ill#134]
Correction to ILL invoice template text

The word California is misspelled in the ILL invoice template.  Inside the top text box the firs line reads "Make checks payable to: The Regents of the University of Calfifornia"   Can you please correct the last word to read "California" ?  Thank you!

**Comment by hweng** [comment]
@EncinasIsabel Sure. Thanks for catching it.

**Comment by EncinasIsabel** [comment]
Thank you Huawei!

**Comment by EncinasIsabel** [comment]
Thank you Huawei!
