### ISSUE TITLE
UCSD Libraries Billing Circ Applications program in Chrome doesn't finish loading

### ISSUE THREAD

**Issue by jessicahilt** [ucsdlib/billing-ill#333]
### Descriptive summary

From ticket #REQ0180576 from Laura Weis - lweis@UCSD.EDU
https://ucsdservicedesk.service-now.com/nav_to.do?uri=sc_request.do%3Fsys_id=f986c066dbca7f809736f35aaf961944%26sysparm_stack=sc_request_list.do%3Fsysparm_query=active=true

User experiencing issue with dimmed screen after logging in on Google Chrome. She isn't able to click on anything. 

Issue does not occur on Firefox, but UI and billing submission process is different and user does not trust using Firefox without clear documentation.

Allison Flick
Additional comments•2019-06-19 13:11:10
I've taken a look at this and determined it's a programmatic error when the site loads in Chrome on a Windows 10 machine. I was able to reproduce this error on Chrome on my laptop with Laura's credentials. The site greys out once the user successfully logs in. I reset the browser, changed the pop-up settings, ensured it was not a security certificate error, and made sure there were no plug-ins interfering. I believe at this point it's a site compatibility issue with Chrome since it works without issue in Firefox. 

The site is https://libraries.ucsd.edu/billing-circ/ Let me know if you cannot access it and I'll grant you access. 

Allison

Talk to Allison if you have further questions as she has tested this extensively.

**Comment by hweng** [comment]
Closed because it is actually Billing-circ issue: https://github.com/ucsdlib/billing-circ/issues/28
