### ISSUE TITLE
Transition plan away from Code Climate

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/billing-ill#98]
The team has agreed to migrate away from Code Climate due to costs. We need to replace with a set of similar services that can integrate into our Circle CI/PR workflow.

Among the obvious (free for Open Source) candidates are:

- [ ] Coveralls (test coverage, we're already using for Code Climate)
- [ ] Hound (PR integration for Rubocop linters)

But, this is an opportunity to review our options before committing.

Let's keep the entire @ucsdlib/developers crew in the loop on this.

**Comment by hweng** [comment]
@mcritchlow Can you see  "hound — No violations found. Woof!" from the pull request https://github.com/ucsdlib/billing-ill/pull/100 ?

**Comment by mcritchlow** [comment]
@hweng - Yep, I see it listed in the list of passed Checks.

**Comment by hweng** [comment]
@mcritchlow Great! Do we want to try .jshintrc configuration? Hound uses JSHint to review JavaScript code.

**Comment by mcritchlow** [comment]
@hweng maybe we could discuss that as part of a separate ticket? I think linting JS is a great idea, but brings up the question of what flavor of JS we're writing. In many newer apps I'm increasingly seeing the usage of ES6, as opposed to say CoffeeScript or older native JS. What do you think?

**Comment by hweng** [comment]
@mcritchlow I agree that we could discuss it separately, as there are several options for JS lint. Or maybe we could choose ESlint rather than JSHint.   Mainly in Hound config, the RuboCop will be enabled to review Ruby code.  haml-lint will be enabled only to billing-ill app. Others lints, such as  scss-lint,  CoffeeLint, might not be necessary to enable because we don't use them in our projects. Let me know if you have any other suggestions. Thanks!

**Comment by mcritchlow** [comment]
Sounds good. I'll setup a ticket, perhaps in our DevelopmentGuides repo for us all to discuss? Then we can implement any documentation changes there and perhaps setup another ticket here in the billing repo so you can pilot out the additional linters?

**Comment by hweng** [comment]
@mcritchlow Sounds good to me.

**Comment by hweng** [comment]
@mcritchlow It looks good to me for testing the hound and coverage/coveralls on billing repo: https://github.com/ucsdlib/billing-ill/pull/102

**Comment by mcritchlow** [comment]
@hweng - agreed. that looks perfect 👍

**Comment by mcritchlow** [comment]
@hweng - one question, the commits look like they're still reference Code Climate. Are you removing that as a separate step/task?

**Comment by hweng** [comment]
@mcritchlow Yes, I tried removing code climate gem and config from billing-ill project, but it got errors in circleCI. I think it need to completely remove the repo from codelimate dashboard. Do you want me to remove the billing-ill from codelimate dashboard?

**Comment by mcritchlow** [comment]
@hweng - yeah i think that would be great. Then we'll know everything involved with transitioning a project away from CodeClimate. Thanks.

**Comment by hweng** [comment]
@mcritchlow Yep, completely removed CodeClimate, see the pull request: https://github.com/ucsdlib/billing-ill/pull/103

**Comment by mcritchlow** [comment]
@hweng - just noticed this ticket is still open for some reason. We can safely close, yes?

**Comment by hweng** [comment]
@mcritchlow Yes, the billing-ill was done migrating away from code climate.
